# Generated by Django 6.0.2 on 2026-02-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mediacontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacontent',
            old_name='title',
            new_name='name',
        ),
    ]
