# Generated by Django 6.0.2 on 2026-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_order_total_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='image',
            field=models.ImageField(default=0, upload_to='supplements/'),
            preserve_default=False,
        ),
    ]
