# Generated by Django 6.0.2 on 2026-03-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='category',
        ),
        migrations.AddField(
            model_name='supplement',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
