# Generated by Django 6.0.2 on 2026-02-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrationprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registrationprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
